using CommunityToolkit.Mvvm.Input;
using SquoundApp_v1.Pages;

namespace SquoundApp_v1.ViewModels
{
    public partial class FooterViewModel : BaseViewModel
    {
        public FooterViewModel()
        {
            Title = "Footer";
        }

        /*
         * Instructs the shell to go to the AboutUs page.
         * We bind this command to the button in the FooterView.xaml file.
         * The code that performs the binding is auto generated by the .NET MAUI framework.
         * The name of the auto-generated command replaces 'Async' with 'Command'.
         */
        [RelayCommand]
        async Task GoToAboutUsPageAsync()
        {
            // This is the call that initiates the change of page.
            await Shell.Current.GoToAsync(nameof(AboutUsPage));
        }
    }
}
